In [2]:
import numpy as np
import pandas as pd

foods = pd.read_csv('MyFoodRatings.csv')

In [4]:
foods.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
Name           12 non-null object
Chicken        12 non-null int64
Mutton         12 non-null int64
Paneer         12 non-null int64
ChowMein       12 non-null int64
SpringRolls    12 non-null int64
Momo           12 non-null int64
Sushi          12 non-null int64
Ramen          12 non-null int64
Tempura        12 non-null int64
dtypes: int64(9), object(1)
memory usage: 1.0+ KB


In [6]:
food_num = foods.drop('Name', axis = 1)
food_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
Chicken        12 non-null int64
Mutton         12 non-null int64
Paneer         12 non-null int64
ChowMein       12 non-null int64
SpringRolls    12 non-null int64
Momo           12 non-null int64
Sushi          12 non-null int64
Ramen          12 non-null int64
Tempura        12 non-null int64
dtypes: int64(9)
memory usage: 944.0 bytes


In [18]:
food_num

Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0         5       5       5         0            0     0      0      0   
1         4       4       4         0            0     0      0      0   
2         3       3       3         0            0     0      0      0   
3         2       2       2         0            0     0      0      0   
4         0       0       0         2            2     2      0      0   
5         0       0       0         1            1     1      0      0   
6         0       0       0         5            3     4      0      0   
7         0       0       0         4            4     4      0      0   
8         0       0       0         0            0     0      2      2   
9         0       0       0         0            0     0      1      1   
10        0       0       0         0            0     0      3      4   
11        0       0       0         0            0     0      2      2   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         4  
9         1  
10        4  
11        2

In [8]:
u, s, vt = np.linalg.svd(food_num, full_matrices=True)

In [17]:
print(u)

[[-6.80413817e-01  0.00000000e+00  0.00000000e+00  2.58908743e-33
   0.00000000e+00  0.00000000e+00  0.00000000e+00  6.83951720e-01
  -2.63148402e-01  1.45752665e-18  0.00000000e+00  0.00000000e+00]
 [-5.44331054e-01  4.96506831e-17  3.85856584e-18 -1.78352620e-17
   2.48253415e-16  8.15015983e-17 -4.42281885e-01 -2.92767967e-01
   6.46521942e-01 -1.62440512e-02  5.53840102e-02 -3.24881025e-02]
 [-4.08248290e-01  4.38559108e-33  3.19773868e-34 -7.06645285e-34
   1.21871670e-32  3.18417792e-33 -4.79822791e-17 -6.51972922e-01
  -6.38955900e-01 -1.00346663e-18  4.00753524e-18 -1.59750734e-18]
 [-2.72165527e-01 -9.93013661e-17 -7.71713167e-18  3.56705241e-17
  -4.96506831e-16 -1.63003197e-16  8.84563769e-01 -1.46383983e-01
   3.23260971e-01  3.24881025e-02 -1.10768020e-01  6.49762050e-02]
 [ 0.00000000e+00 -3.26217015e-01 -5.18387119e-17  2.39611568e-16
  -2.89928697e-01 -1.09495032e-15 -1.33251006e-01  0.00000000e+00
   0.00000000e+00  2.18234113e-01 -7.44068101e-01  4.36468226e-01]
 [ 0.

In [12]:
u.shape

(12, 12)

In [13]:
vt.shape

(9, 9)

In [14]:
np.diag(s[:3])

array([[12.72792206,  0.        ,  0.        ],
       [ 0.        , 10.57703788,  0.        ],
       [ 0.        ,  0.        ,  8.84826058]])

In [19]:
print(vt[:3,:])

[[-0.57735027 -0.57735027 -0.57735027  0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.         -0.63787511 -0.51226147 -0.57506829
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
  -0.47616345 -0.55763787 -0.67993263]]


In [20]:
food_all = pd.read_csv('FoodRatings_all_same_5.csv')
food_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
Name           12 non-null object
Chicken        12 non-null int64
Mutton         12 non-null int64
Paneer         12 non-null int64
ChowMein       12 non-null int64
SpringRolls    12 non-null int64
Momo           12 non-null int64
Sushi          12 non-null int64
Ramen          12 non-null int64
Tempura        12 non-null int64
dtypes: int64(9), object(1)
memory usage: 1.0+ KB


In [21]:
food_all

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0     A        5       5       5         0            0     0      0      0   
1     B        5       5       5         0            0     0      0      0   
2     C        5       5       5         0            0     0      0      0   
3     D        5       5       5         0            0     0      0      0   
4     E        0       0       0         5            5     5      0      0   
5     F        0       0       0         5            5     5      0      0   
6     G        0       0       0         5            5     5      0      0   
7     H        0       0       0         5            5     5      0      0   
8     I        0       0       0         0            0     0      5      5   
9     J        0       0       0         0            0     0      5      5   
10    K        0       0       0         0            0     0      5      5   
11    L        0       0       0         0            0     0      5      5   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         5  
9         5  
10        5  
11        5

In [22]:
food_all.drop('Name',axis=1,inplace=True)

In [23]:
u, s, vt = np.linalg.svd(food_all, full_matrices=True)

In [27]:
s

array([1.73205081e+01, 1.73205081e+01, 1.73205081e+01, 3.92523115e-16,
       2.79802815e-49, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])

In [28]:
food_z = pd.read_csv('FoodRatings_all_same_5_4_3.csv')
food_z.drop('Name',axis=1,inplace=True)

In [29]:
u, s, vt = np.linalg.svd(food_z, full_matrices=True)
s

array([1.73205081e+01, 1.38564065e+01, 1.03923048e+01, 3.92523115e-16,
       2.79802815e-49, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])

In [30]:
np.diag(s[:3])

array([[17.32050808,  0.        ,  0.        ],
       [ 0.        , 13.85640646,  0.        ],
       [ 0.        ,  0.        , 10.39230485]])